# Generated by Django 4.0.3 on 2022-04-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_likeforanswer_likeforquestion_remove_answer_likes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeforanswer',
            unique_together={('owner', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='likeforquestion',
            unique_together={('owner', 'question')},
        ),
    ]
